Add jugend hackt badge
Jugendhackt/kfdw-backend pull request #12
Opened 2019-10-01 09:40 UTC by magicmarvman

Add jugendhackt badge

2019-10-05 18:28 UTC, jens1o submitted a review, later dismissed

2019-10-05 18:29 UTC, jens1o requested changes
Could you modify the ALT-text to provide a meaningful alternative for impaired users, please?

2019-10-05 18:38 UTC, magicmarvman commented
Yep, should fit now. Thanks for the review!

2019-10-05 18:47 UTC, jens1o commented on README.md
> +[![Made at Jugend hackt Franfurt 2018](https://jhbadge.com/?year=2018&evt=ffm)](https://jugendhackt.org)
It's `Frankfurt` ;)

2019-10-05 18:56 UTC, magicmarvman commented on README.md
> +[![Made at Jugend hackt Franfurt 2018](https://jhbadge.com/?year=2018&evt=ffm)](https://jugendhackt.org)
Fixed :)

2019-10-05 18:56 UTC, magicmarvman commented
Fixed :)

2019-10-06 06:59 UTC, jens1o approved these changes

2019-10-06 07:00 UTC, merged